

CREATE TABLE dio.reserva (
	id INT COMMENT "IDENTIFICADOR UNICO DA RESERVA",
    id_usuario INT COMMENT "REFERENCIA AO ID DO USUARIO QUE FEZ A RESERVA",
    id_destino INT COMMENT "REFERENCIA AO ID DO DESTINO DA RESERVA",
    data DATE COMMENT "DATA DA RESERVA",
    status VARCHAR(255) DEFAULT 'pendente' COMMENT 'STATUS DA RESERVA (confirmada, pendente, cancelada, etc.)'
);